# Análise Exploratória de Dados Automática
Este notebook itera sobre todos os ficheiros CSV presentes em `data/processed/` e gera uma análise exploratória rápida para cada um, tirando partido das capacidades visuais do Jupyter.

In [ ]:
import os
import pandas as pd
from IPython.display import display, Markdown

In [ ]:
current_dir = os.getcwd()
root_dir = os.path.dirname(current_dir) if os.path.basename(current_dir) == 'notebooks' else current_dir
data_dir = os.path.join(root_dir, 'data', 'processed')

if not os.path.exists(data_dir):
    print(f"Error: Directory not found {data_dir}")
    print("Execute 'src/data_prep.py' script to generate data first.")
    csv_files = []
else:
    csv_files = [f for f in os.listdir(data_dir) if f.endswith('.csv')]
    print(f"Found {len(csv_files)} datasets. Initiating analysis...")

Found 14 datasets. Initiating analysis...

In [ ]:
for file in csv_files:
    file_path = os.path.join(data_dir, file)
    dataset_name = os.path.splitext(file)[0]
    
    display(Markdown(f"<br>\n\n---\n# Dataset: **{dataset_name}**"))
    
    try:
        df = pd.read_csv(file_path)
        
        display(Markdown(f"### General Info\n- **Number of Rows:** {df.shape[0]}\n- **Number of Columns:** {df.shape[1]}"))
        
        display(Markdown("### Data Types and Non-Null Counts"))
        df.info()
        
        display(Markdown("### Data Sample (First 5 Rows)"))
        display(df.head())
        
        display(Markdown("### Descriptive Statistics"))
        display(df.describe(include='all'))
        
        display(Markdown("### Missing Values"))
        nulos = df.isnull().sum()
        display(nulos[nulos > 0].to_frame(name='Null Values') if nulos.sum() > 0 else "None found.")
        
    except Exception as e:
        print(f"Error processing {file}: {e}")

<br>

---
# Dataset: **acesso_consultas**

### General Info
- **Number of Rows:** 6212
- **Number of Columns:** 10

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 6212 entries, 0 to 6211
Data columns (total 10 columns):
 #   Column                                                                       Non-Null Count  Dtype
---  ------                                                                       --------------  -----
 0   tempo                                                                        6212 non-null   str
 1   regiao                                                                       6212 non-null   str
 2   entidade                                                                     6212 non-null   str
 3   localizacao_geografica                                                       6212 non-null   str
 4   taxa_de_utilizacao_global_de_consultas_medicas_1_ano                         6212 non-null   float64
 5   no_utentes_pelo_menos_1_consulta_medicas_presencial_ou_nao_presencial_1_ano  6212 non-null   int64
 6   taxa_de_utilizacao_de_consultas_medicas_3_anos                               6212 non-null   float64
 7   no_utentes_com_pelo_menos_1_consulta_medica_em_3_anos                        6212 non-null   int64
 8   ano                                                                          6212 non-null   int64
 9   mes                                                                          6212 non-null   int64
dtypes: float64(2), int64(4), str(4)
memory usage: 485.4 KB

### Data Sample (First 5 Rows)

,tempo,regiao,entidade,localizacao_geografica,taxa_de_utilizacao_global_de_consultas_medicas_1_ano,no_utentes_pelo_menos_1_consulta_medicas_presencial_ou_nao_presencial_1_ano,taxa_de_utilizacao_de_consultas_medicas_3_anos,no_utentes_com_pelo_menos_1_consulta_medica_em_3_anos,ano,mes
0,2016-01-01,Alentejo,Área dos CSP da ULS Alto Alentejo,"39.2967086, -7.4284755",25.57838,30205,83.16679,98210,2016,1
1,2016-01-01,Centro,ACES Baixo Mondego,"40.2150023, -8.4071805",19.31442,73829,69.63123,266164,2016,1
2,2016-01-01,Lisboa e Vale do Tejo,Área dos CSP da ULS Arrábida,"38.5324373, -8.8627453",18.78958,43614,73.82926,171371,2016,1
3,2016-01-01,Lisboa e Vale do Tejo,ACES Sintra,"38.7519209, -9.2753636",14.82209,53503,68.72105,248061,2016,1
4,2016-01-01,Lisboa e Vale do Tejo,ACES Lisboa Norte,"38.7396924, -9.168506",14.63721,36437,69.43929,172858,2016,1

### Descriptive Statistics

,tempo,regiao,entidade,localizacao_geografica,taxa_de_utilizacao_global_de_consultas_medicas_1_ano,no_utentes_pelo_menos_1_consulta_medicas_presencial_ou_nao_presencial_1_ano,taxa_de_utilizacao_de_consultas_medicas_3_anos,no_utentes_com_pelo_menos_1_consulta_medica_em_3_anos,ano,mes
count,6212,6212,6212,6212,6212.000000,6212.000000,6212.000000,6212.000000,6212.000000,6212.000000
unique,120,5,76,122,NaN,NaN,NaN,NaN,NaN,NaN
top,2016-01-01,Norte,Área dos CSP da ULS Arrábida,"40.2150023, -8.4071805",NaN,NaN,NaN,NaN,NaN,NaN
freq,55,2640,120,92,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,53.896549,105188.219575,82.820559,163004.705570,2020.253703,6.500966
std,NaN,NaN,NaN,NaN,15.361748,56675.013205,6.524166,74266.213033,2.774872,3.453232
min,NaN,NaN,NaN,NaN,13.695470,8152.000000,62.848690,27031.000000,2016.000000,1.000000
25%,NaN,NaN,NaN,NaN,44.210215,65186.000000,78.351190,110424.500000,2018.000000,3.000000
50%,NaN,NaN,NaN,NaN,56.324765,95856.000000,84.868250,148961.000000,2020.000000,7.000000
75%,NaN,NaN,NaN,NaN,66.428335,129398.000000,87.745825,191485.000000,2023.000000,10.000000
max,NaN,NaN,NaN,NaN,81.882650,383980.000000,94.024360,448270.000000,2025.000000,12.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **master_dataset**

### General Info
- **Number of Rows:** 8163
- **Number of Columns:** 20

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 8163 entries, 0 to 8162
Data columns (total 20 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   regiao                                     8163 non-null   str
 1   instituicao                                8163 non-null   str
 2   ano                                        8163 non-null   int64
 3   mes                                        8163 non-null   int64
 4   ebitda                                     8163 non-null   float64
 5   gastos_operacionais                        8163 non-null   float64
 6   rendimentos_operacionais                   8163 non-null   float64
 7   resultado_liquido                          8163 non-null   float64
 8   resultados_operacionais                    8163 non-null   float64
 9   urgencias_geral                            8163 non-null   float64
 10  total_urgencias                            8163 non-null   float64
 11  doentes_saidos                             8163 non-null   float64
 12  dias_de_internamento                       8163 non-null   float64
 13  no_intervencoes_cirurgicas_programadas     8163 non-null   float64
 14  no_intervencoes_cirurgicas_convencionais   8163 non-null   float64
 15  no_intervencoes_cirurgicas_de_ambulatorio  8163 non-null   float64
 16  no_intervencoes_cirurgicas_urgentes        8163 non-null   float64
 17  no_de_consultas_medicas_total              8163 non-null   float64
 18  no_de_primeiras_consultas                  8163 non-null   float64
 19  no_de_consultas_subsequentes               8163 non-null   float64
dtypes: float64(16), int64(2), str(2)
memory usage: 1.2 MB

### Data Sample (First 5 Rows)

,regiao,instituicao,ano,mes,ebitda,gastos_operacionais,rendimentos_operacionais,resultado_liquido,resultados_operacionais,urgencias_geral,total_urgencias,doentes_saidos,dias_de_internamento,no_intervencoes_cirurgicas_programadas,no_intervencoes_cirurgicas_convencionais,no_intervencoes_cirurgicas_de_ambulatorio,no_intervencoes_cirurgicas_urgentes,no_de_consultas_medicas_total,no_de_primeiras_consultas,no_de_consultas_subsequentes
0,Alentejo,Hospital Espírito Santo de Évora,2016,1,-434271.45,6658966.61,6011770.52,-671686.95,-647196.09,4600.0,6705.0,1091.0,7739.0,1016.0,365.0,651.0,135.0,15669.0,4855.0,10814.0
1,Alentejo,Hospital Espírito Santo de Évora,2016,2,-1055970.62,13705011.68,12224095.79,-1388851.48,-1480915.89,8829.0,12629.0,2122.0,15047.0,2082.0,734.0,1348.0,264.0,31400.0,9688.0,21712.0
2,Alentejo,Hospital Espírito Santo de Évora,2016,3,-1142753.35,20705767.00,18922454.36,-1651677.69,-1783312.64,13209.0,18624.0,3139.0,22364.0,3169.0,1145.0,2024.0,382.0,48131.0,14752.0,33379.0
3,Alentejo,Hospital Espírito Santo de Évora,2016,4,-1800956.00,27840405.52,25186147.68,-2302325.97,-2654257.84,17605.0,24808.0,4136.0,29617.0,4296.0,1538.0,2758.0,546.0,64082.0,19646.0,44436.0
4,Alentejo,Hospital Espírito Santo de Évora,2016,5,-2392387.54,34981080.80,31522123.71,-3087538.69,-3458957.09,22337.0,31556.0,5165.0,37014.0,5461.0,1963.0,3498.0,693.0,81420.0,24861.0,56559.0

### Descriptive Statistics

,regiao,instituicao,ano,mes,ebitda,gastos_operacionais,rendimentos_operacionais,resultado_liquido,resultados_operacionais,urgencias_geral,total_urgencias,doentes_saidos,dias_de_internamento,no_intervencoes_cirurgicas_programadas,no_intervencoes_cirurgicas_convencionais,no_intervencoes_cirurgicas_de_ambulatorio,no_intervencoes_cirurgicas_urgentes,no_de_consultas_medicas_total,no_de_primeiras_consultas,no_de_consultas_subsequentes
count,8163,8163,8163.000000,8163.000000,8.163000e+03,8.163000e+03,8.163000e+03,8.163000e+03,8.163000e+03,8163.000000,8163.000000,8163.000000,8163.000000,8163.000000,8163.000000,8163.000000,8163.000000,8.163000e+03,8163.000000,8163.000000
unique,6,116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,Norte,Unidade Local de Saúde do Baixo Alentejo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,2811,120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,2020.361264,6.497979,-7.212814e+06,6.416752e+07,5.571270e+07,-8.505060e+06,-8.546390e+06,34563.983952,47030.436849,6104.736616,52669.522479,5115.591082,1646.995467,3468.595614,776.379762,1.017571e+05,28850.146270,72906.963004
std,NaN,NaN,2.812390,3.449583,1.460514e+07,1.047761e+08,9.077846e+07,1.625743e+07,1.628299e+07,43394.298243,59847.535638,8127.785653,71208.470796,7373.351857,2512.204977,5001.549076,1164.160439,1.445765e+05,39476.941062,105684.083662
min,NaN,NaN,2016.000000,1.000000,-1.688819e+08,0.000000e+00,-6.411547e+06,-1.893682e+08,-1.886743e+08,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
25%,NaN,NaN,2018.000000,4.000000,-9.325541e+06,0.000000e+00,0.000000e+00,-1.104082e+07,-1.110258e+07,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000e+00,0.000000,0.000000
50%,NaN,NaN,2020.000000,6.000000,-7.947452e+05,2.208227e+07,1.946116e+07,-1.364116e+06,-1.438592e+06,16943.000000,22692.000000,3194.000000,27197.000000,2471.000000,733.000000,1551.000000,320.000000,4.896500e+04,14753.000000,34181.000000
75%,NaN,NaN,2023.000000,9.000000,0.000000e+00,8.534226e+07,7.375347e+07,0.000000e+00,0.000000e+00,58424.000000,76999.500000,9168.500000,77925.000000,6994.000000,2157.000000,4856.000000,1119.000000,1.410515e+05,40664.000000,99998.500000
max,NaN,NaN,2025.000000,12.000000,1.379784e+08,1.006721e+09,8.508979e+08,1.380264e+08,1.379784e+08,292003.000000,380759.000000,60205.000000,503965.000000,59252.000000,20417.000000,38967.000000,8972.000000,1.000962e+06,259515.000000,741447.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **trabalhadores_grupo_profissional**

### General Info
- **Number of Rows:** 7332
- **Number of Columns:** 21

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 7332 entries, 0 to 7331
Data columns (total 21 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   periodo                   7332 non-null   str
 1   regiao                    7332 non-null   str
 2   instituicao               7332 non-null   str
 3   localizacao_geografica    7332 non-null   str
 4   medicos_s_internos        7332 non-null   float64
 5   medicos_internos          7332 non-null   float64
 6   enfermeiros               7332 non-null   float64
 7   tss                       7332 non-null   float64
 8   farmaceuticos             7332 non-null   float64
 9   farmaceuticos_residentes  7332 non-null   float64
 10  tdt                       7332 non-null   float64
 11  at                        7332 non-null   float64
 12  ao                        7332 non-null   float64
 13  tas                       7332 non-null   float64
 14  ao0                       7332 non-null   float64
 15  ts                        7332 non-null   float64
 16  informaticos              7332 non-null   float64
 17  outros                    7332 non-null   float64
 18  total_geral               7332 non-null   int64
 19  ano                       7332 non-null   int64
 20  mes                       7332 non-null   int64
dtypes: float64(14), int64(3), str(4)
memory usage: 1.2 MB

### Data Sample (First 5 Rows)

,periodo,regiao,instituicao,localizacao_geografica,medicos_s_internos,medicos_internos,enfermeiros,tss,farmaceuticos,farmaceuticos_residentes,...,at,ao,tas,ao0,ts,informaticos,outros,total_geral,ano,mes
0,2016-01-01,Alentejo,"Administração Regional de Saúde do Alentejo, I.P.","38.565715, -7.91162",114.0,35.0,191.0,18.0,0.0,0.0,...,182.0,99.0,0.0,0.0,0.0,0.0,85.0,747,2016,1
1,2016-01-01,Norte,"Administração Regional de Saúde do Norte, I.P.","41.157454, -8.604431",1886.0,909.0,2620.0,138.0,0.0,0.0,...,1914.0,869.0,0.0,0.0,0.0,0.0,421.0,8951,2016,1
2,2016-02-01,Lisboa e Vale do Tejo,Administração Regional de Saúde de Lisboa e Va...,"38.748879, -9.139606",1799.0,734.0,2434.0,164.0,0.0,0.0,...,1791.0,752.0,0.0,0.0,0.0,0.0,390.0,8361,2016,2
3,2016-03-01,Algarve,"Administração Regional de Saúde do Algarve, I.P.","37.027122, -7.946842",231.0,94.0,418.0,35.0,0.0,0.0,...,315.0,240.0,0.0,0.0,0.0,0.0,105.0,1582,2016,3
4,2016-03-01,Centro,"Administração Regional de Saúde do Centro, I.P.","40.203782, -8.419176",937.0,351.0,1194.0,74.0,0.0,0.0,...,1021.0,500.0,0.0,0.0,0.0,0.0,236.0,4464,2016,3

### Descriptive Statistics

,periodo,regiao,instituicao,localizacao_geografica,medicos_s_internos,medicos_internos,enfermeiros,tss,farmaceuticos,farmaceuticos_residentes,...,at,ao,tas,ao0,ts,informaticos,outros,total_geral,ano,mes
count,7332,7332,7332,7332,7332.000000,7332.000000,7332.000000,7332.000000,7332.000000,7332.000000,...,7332.000000,7332.000000,7332.000000,7332.000000,7332.000000,7332.000000,7332.000000,7332.000000,7332.000000,7332.000000
unique,120,6,104,65,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2022-02-01,Norte,"Administração Central do Sistema de Saúde, I.P.",Desconhecido,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,64,1952,120,421,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,325.571877,167.304965,764.217949,21.843562,6.322831,1.084424,...,278.319285,409.335788,39.680578,8.689171,63.773186,7.972586,54.685352,2296.276869,2020.464948,6.496727
std,NaN,NaN,NaN,NaN,410.562584,205.224487,774.047068,30.451895,11.399917,2.919666,...,360.170644,433.222602,178.421275,39.285927,78.405154,7.584161,130.500596,2271.241727,2.836998,3.454617
min,NaN,NaN,NaN,NaN,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2016.000000,1.000000
25%,NaN,NaN,NaN,NaN,38.000000,21.000000,172.000000,3.000000,0.000000,0.000000,...,79.000000,27.750000,0.000000,0.000000,9.000000,1.000000,13.000000,584.000000,2018.000000,3.000000
50%,NaN,NaN,NaN,NaN,196.000000,97.000000,613.000000,12.000000,0.000000,0.000000,...,186.000000,346.000000,0.000000,0.000000,43.000000,7.000000,25.000000,1784.000000,2020.000000,6.000000
75%,NaN,NaN,NaN,NaN,401.000000,216.000000,1013.000000,27.000000,9.000000,0.000000,...,305.000000,599.000000,0.000000,0.000000,77.000000,11.000000,45.000000,2856.500000,2023.000000,9.250000
max,NaN,NaN,NaN,NaN,2218.000000,917.000000,3828.000000,166.000000,65.000000,24.000000,...,2395.000000,2265.000000,1981.000000,475.000000,505.000000,39.000000,1083.000000,10550.000000,2025.000000,12.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **trabalhadores_modalidade**

### General Info
- **Number of Rows:** 95337
- **Number of Columns:** 8

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 95337 entries, 0 to 95336
Data columns (total 8 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   tempo                     95337 non-null  str
 1   regiao                    95337 non-null  str
 2   entidade                  95337 non-null  str
 3   localizacao_geografica    95337 non-null  str
 4   modalidade_de_vinculacao  95337 non-null  str
 5   no_trabalhadores          95337 non-null  int64
 6   ano                       95337 non-null  int64
 7   mes                       95337 non-null  int64
dtypes: int64(3), str(5)
memory usage: 5.8 MB

### Data Sample (First 5 Rows)

,tempo,regiao,entidade,localizacao_geografica,modalidade_de_vinculacao,no_trabalhadores,ano,mes
0,2020-05-01,Centro,Hospital Distrital da Figueira da Foz,"40.117897, -8.8586755",CT p/ tempo Indeterminado no âmbito Cód. Trabalho,320,2020,5
1,2020-05-01,Centro,Hospital Distrital da Figueira da Foz,"40.117897, -8.8586755",CTR certo no âmbito do Código Trabalho,25,2020,5
2,2020-05-01,Centro,Hospital Dr. Francisco Zagalo,"40.8571967, -8.6318023",Nomeação Transitória p/ Tempo determinável,0,2020,5
3,2020-05-01,Centro,Hospital Dr. Francisco Zagalo,"40.8571967, -8.6318023",CT em Funções Públicas p/ Tempo Indeterminado,169,2020,5
4,2020-05-01,Centro,Instituto Português de Oncologia de Coimbra F. G.,"40.2162514, -8.4103814",Nomeação Transitória p/ Tempo determinado,0,2020,5

### Descriptive Statistics

,tempo,regiao,entidade,localizacao_geografica,modalidade_de_vinculacao,no_trabalhadores,ano,mes
count,95337,95337,95337,95337,95337,95337.000000,95337.000000,95337.000000
unique,120,5,122,69,13,NaN,NaN,NaN
top,2023-01-01,Lisboa e Vale do Tejo,"Administração Central do Sistema de Saúde, I.P.","38.7362218, -9.1463126",CT p/ tempo Indeterminado no âmbito Cód. Trabalho,NaN,NaN,NaN
freq,845,39463,1560,3050,7339,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,180.229743,2020.508606,6.496156
std,NaN,NaN,NaN,NaN,NaN,605.421757,2.835955,3.453091
min,NaN,NaN,NaN,NaN,NaN,0.000000,2016.000000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,0.000000,2018.000000,3.000000
50%,NaN,NaN,NaN,NaN,NaN,3.000000,2021.000000,6.000000
75%,NaN,NaN,NaN,NaN,NaN,50.000000,2023.000000,9.000000
max,NaN,NaN,NaN,NaN,NaN,8256.000000,2025.000000,12.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **contas_sns**

### General Info
- **Number of Rows:** 120
- **Number of Columns:** 69

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 120 entries, 0 to 119
Data columns (total 69 columns):
 #   Column                                                                                                Non-Null Count  Dtype
---  ------                                                                                                --------------  -----
 0   tempo                                                                                                 120 non-null    str
 1   orcamento_receita_corrente                                                                            120 non-null    float64
 2   orcamento_receita_fiscal                                                                              120 non-null    float64
 3   orcamento_impostos_directos                                                                           120 non-null    float64
 4   orcamento_impostos_indirectos                                                                         120 non-null    float64
 5   orcamento_contribuicoes_de_seguranca_social                                                           120 non-null    float64
 6   orcamento_outras_receitas_correntes                                                                   120 non-null    float64
 7   orcamento_outras_receitas_correntes_das_quais_transferencias_de_outros_subsectores_das_ap             120 non-null    float64
 8   orcamento_receita_de_capital                                                                          120 non-null    float64
 9   orcamento_receita_de_capital_das_quais_transferencias_de_outros_subsectores_das_ap                    120 non-null    float64
 10  orcamento_receita_efectiva                                                                            120 non-null    float64
 11  orcamento_despesa_corrente                                                                            120 non-null    float64
 12  orcamento_consumo_publico                                                                             120 non-null    float64
 13  orcamento_despesas_com_o_pessoal                                                                      120 non-null    float64
 14  orcamento_remuneracoes_certas_e_permanentes                                                           120 non-null    float64
 15  orcamento_abonos_variaveis_ou_eventuais                                                               120 non-null    float64
 16  orcamento_seguranca_social                                                                            120 non-null    float64
 17  orcamento_aquisicao_de_bens_e_servicos                                                                120 non-null    float64
 18  orcamento_produtos_vendidos_em_farmacias                                                              120 non-null    float64
 19  orcamento_meios_complementares_de_diagnostico_e_terapeutica                                           120 non-null    float64
 20  orcamento_parcerias_publico_privadas_ppp                                                              120 non-null    float64
 21  orcamento_aquisicao_de_bens_compras_inventarios                                                       120 non-null    float64
 22  orcamento_outras_aquisicoes_de_bens_e_servicos                                                        120 non-null    float64
 23  orcamento_outras_despesas_correntes                                                                   120 non-null    float64
 24  orcamento_juros_e_outros_encargos                                                                     120 non-null    float64
 25  orcamento_transferencias_correntes                                                                    120 non-null    float64
 26  orcamento_transferencias_correntes_das_quais_transferencias_para_outros_subsectores_das_ap            120 non-null    float64
 27  orcamento_despesa_de_capital                                                                          120 non-null    float64
 28  orcamento_investimentos                                                                               120 non-null    float64
 29  orcamento_transferencias_de_capital                                                                   120 non-null    float64
 30  orcamento_transferencias_de_capital_das_quais_transferencias_para_outros_subsectores_das_ap           120 non-null    float64
 31  orcamento_outras_despesas_de_capital                                                                  120 non-null    float64
 32  orcamento_despesa_efectiva                                                                            120 non-null    float64
 33  orcamento_saldo_global                                                                                120 non-null    float64
 34  execucao_acumulada_receita_corrente                                                                   120 non-null    float64
 35  execucao_acumulada_receita_fiscal                                                                     120 non-null    float64
 36  execucao_acumulada_impostos_directos                                                                  120 non-null    float64
 37  execucao_acumulada_impostos_indirectos                                                                120 non-null    float64
 38  execucao_acumulada_contribuicoes_de_seguranca_social                                                  120 non-null    float64
 39  execucao_acumulada_outras_receitas_correntes                                                          120 non-null    float64
 40  execucao_acumulada_outras_receitas_correntes_das_quais_transferencias_de_outros_subsectores_das_ap    120 non-null    float64
 41  execucao_acumulada_receita_de_capital                                                                 120 non-null    float64
 42  execucao_acumulada_receita_de_capital_das_quais_transferencias_de_outros_subsectores_das_ap           120 non-null    float64
 43  execucao_acumulada_receita_efectiva                                                                   120 non-null    float64
 44  execucao_acumulada_despesa_corrente                                                                   120 non-null    float64
 45  execucao_acumulada_consumo_publico                                                                    120 non-null    float64
 46  execucao_acumulada_despesas_com_o_pessoal                                                             120 non-null    float64
 47  execucao_acumulada_remuneracoes_certas_e_permanentes                                                  120 non-null    float64
 48  execucao_acumulada_abonos_variaveis_ou_eventuais                                                      120 non-null    float64
 49  execucao_acumulada_seguranca_social                                                                   120 non-null    float64
 50  execucao_acumulada_aquisicao_de_bens_e_servicos                                                       120 non-null    float64
 51  execucao_acumulada_produtos_vendidos_em_farmacias                                                     120 non-null    float64
 52  execucao_acumulada_meios_complementares_de_diagnostico_e_terapeutica                                  120 non-null    float64
 53  execucao_acumulada_parcerias_publico_privadas_ppp                                                     120 non-null    float64
 54  execucao_acumulada_aquisicao_de_bens_compras_inventarios                                              120 non-null    float64
 55  execucao_acumulada_outras_aquisicoes_de_bens_e_servicos                                               120 non-null    float64
 56  execucao_acumulada_outras_despesas_correntes                                                          120 non-null    float64
 57  execucao_acumulada_juros_e_outros_encargos                                                            120 non-null    float64
 58  execucao_acumulada_transferencias_correntes                                                           120 non-null    float64
 59  execucao_acumulada_transferencias_correntes_das_quais_transferencias_para_outros_subsectores_das_ap   120 non-null    float64
 60  execucao_acumulada_despesa_de_capital                                                                 120 non-null    float64
 61  execucao_acumulada_investimentos                                                                      120 non-null    float64
 62  execucao_acumulada_transferencias_de_capital                                                          120 non-null    float64
 63  execucao_acumulada_transferencias_de_capital_das_quais_transferencias_para_outros_subsectores_das_ap  120 non-null    float64
 64  execucao_acumulada_outras_despesas_de_capital                                                         120 non-null    float64
 65  execucao_acumulada_despesa_efectiva                                                                   120 non-null    float64
 66  execucao_acumulada_saldo_global                                                                       120 non-null    float64
 67  ano                                                                                                   120 non-null    int64
 68  mes                                                                                                   120 non-null    int64
dtypes: float64(66), int64(2), str(1)
memory usage: 64.8 KB

### Data Sample (First 5 Rows)

,tempo,orcamento_receita_corrente,orcamento_receita_fiscal,orcamento_impostos_directos,orcamento_impostos_indirectos,orcamento_contribuicoes_de_seguranca_social,orcamento_outras_receitas_correntes,orcamento_outras_receitas_correntes_das_quais_transferencias_de_outros_subsectores_das_ap,orcamento_receita_de_capital,orcamento_receita_de_capital_das_quais_transferencias_de_outros_subsectores_das_ap,...,execucao_acumulada_transferencias_correntes_das_quais_transferencias_para_outros_subsectores_das_ap,execucao_acumulada_despesa_de_capital,execucao_acumulada_investimentos,execucao_acumulada_transferencias_de_capital,execucao_acumulada_transferencias_de_capital_das_quais_transferencias_para_outros_subsectores_das_ap,execucao_acumulada_outras_despesas_de_capital,execucao_acumulada_despesa_efectiva,execucao_acumulada_saldo_global,ano,mes
0,2016-05-01,8691.0,104.0,104.0,0.0,0.0,8587.0,7943.0,63.0,0.0,...,0.0,30.3,30.2,0.1,0.0,0.0,3686.9,-118.8,2016,5
1,2016-07-01,8691.0,104.0,104.0,0.0,0.0,8587.0,7943.0,63.0,0.0,...,0.0,48.6,48.2,0.4,0.0,0.0,5087.0,1.7,2016,7
2,2016-08-01,8691.0,104.0,104.0,0.0,0.0,8587.0,7943.0,63.0,0.0,...,0.0,54.5,54.1,0.4,0.0,0.0,5826.3,-20.0,2016,8
3,2016-12-01,8691.0,104.0,104.0,0.0,0.0,8587.0,7943.0,63.0,0.0,...,0.0,106.3,105.5,0.8,0.0,0.0,9243.7,-301.1,2016,12
4,2017-05-01,8803.4,130.7,130.7,0.0,0.0,8672.7,8094.1,78.7,0.0,...,0.0,18.2,18.0,0.2,0.0,0.0,3854.5,-150.5,2017,5

### Descriptive Statistics

,tempo,orcamento_receita_corrente,orcamento_receita_fiscal,orcamento_impostos_directos,orcamento_impostos_indirectos,orcamento_contribuicoes_de_seguranca_social,orcamento_outras_receitas_correntes,orcamento_outras_receitas_correntes_das_quais_transferencias_de_outros_subsectores_das_ap,orcamento_receita_de_capital,orcamento_receita_de_capital_das_quais_transferencias_de_outros_subsectores_das_ap,...,execucao_acumulada_transferencias_correntes_das_quais_transferencias_para_outros_subsectores_das_ap,execucao_acumulada_despesa_de_capital,execucao_acumulada_investimentos,execucao_acumulada_transferencias_de_capital,execucao_acumulada_transferencias_de_capital_das_quais_transferencias_para_outros_subsectores_das_ap,execucao_acumulada_outras_despesas_de_capital,execucao_acumulada_despesa_efectiva,execucao_acumulada_saldo_global,ano,mes
count,120,120.000000,120.000000,120.000000,120.000000,120.0,120.000000,120.000000,120.000000,120.0,...,120.0,120.000000,120.00000,120.000000,120.0,120.0,120.000000,120.000000,120.000000,120.000000
unique,120,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2016-05-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,11495.224272,117.346667,104.486667,12.860000,0.0,11377.875297,10592.523550,228.498443,0.0,...,0.0,96.923333,90.31500,6.608333,0.0,0.0,6375.564750,-248.740195,2020.500000,6.500000
std,NaN,2381.055236,10.418019,36.298640,38.741762,0.0,2380.425213,2147.459980,184.259619,0.0,...,0.0,95.156242,84.55658,17.571040,0.0,0.0,3832.460162,308.557595,2.884324,3.466527
min,NaN,8691.000000,104.000000,0.000000,0.000000,0.0,8587.000000,7943.000000,55.700000,0.0,...,0.0,0.300000,0.30000,0.000000,0.0,0.0,671.100000,-1377.553191,2016.000000,1.000000
25%,NaN,9303.000000,110.000000,106.500000,0.000000,0.0,9193.000000,8594.000000,111.250000,0.0,...,0.0,24.050000,23.90000,0.100000,0.0,0.0,3216.650000,-376.890229,2018.000000,3.750000
50%,NaN,11138.862253,113.900000,113.000000,0.000000,0.0,11009.412253,10448.297473,123.500000,0.0,...,0.0,67.050000,65.50000,0.400000,0.0,0.0,6064.730000,-151.431552,2020.500000,6.500000
75%,NaN,13649.292166,128.600000,122.000000,0.000000,0.0,13535.392166,12320.892166,299.286947,0.0,...,0.0,140.625000,135.55000,2.200000,0.0,0.0,9113.975000,-37.298276,2023.000000,9.250000
max,NaN,15951.580000,136.900000,136.900000,128.600000,0.0,15822.980000,14366.580000,578.400000,0.0,...,0.0,442.300000,357.40000,103.400000,0.0,0.0,16961.500000,224.200000,2025.000000,12.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **cirurgias_ambulatorio**

### General Info
- **Number of Rows:** 5725
- **Number of Columns:** 8

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 5725 entries, 0 to 5724
Data columns (total 8 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   tempo                                                                 5725 non-null   str
 1   regiao                                                                5725 non-null   str
 2   instituicao                                                           5725 non-null   str
 3   localizacao_geografica                                                5725 non-null   str
 4   no_episodios_cirurgicos_ambulat_com_procedimentos_ambulatorizaveis    5725 non-null   int64
 5   no_episodios_cirurgicos_ambulat_e_intern_com_proced_ambulatorizaveis  5725 non-null   int64
 6   ano                                                                   5725 non-null   int64
 7   mes                                                                   5725 non-null   int64
dtypes: int64(4), str(4)
memory usage: 357.9 KB

### Data Sample (First 5 Rows)

,tempo,regiao,instituicao,localizacao_geografica,no_episodios_cirurgicos_ambulat_com_procedimentos_ambulatorizaveis,no_episodios_cirurgicos_ambulat_e_intern_com_proced_ambulatorizaveis,ano,mes
0,2024-01-01,Centro,Instituto Português de Oncologia de Coimbra F. G.,"40.217, -8.40991",6,25,2024,1
1,2024-01-01,Centro,Unidade Local de Saúde Castelo Branco,"39.822737, -7.499876",143,189,2024,1
2,2024-01-01,Lisboa e Vale do Tejo,Unidade Local de Saúde de Amadora/Sintra,"38.7436332060551, -9.0",713,770,2024,1
3,2024-01-01,Norte,Unidade Local de Saúde de São João,"41.1833, -8.60193",752,980,2024,1
4,2024-01-01,Norte,Unidade Local de Saúde de Vila Nova de Gaia/Es...,"41.1254463195801, -8.0",800,894,2024,1

### Descriptive Statistics

,tempo,regiao,instituicao,localizacao_geografica,no_episodios_cirurgicos_ambulat_com_procedimentos_ambulatorizaveis,no_episodios_cirurgicos_ambulat_e_intern_com_proced_ambulatorizaveis,ano,mes
count,5725,5725,5725,5725,5725.000000,5725.000000,5725.000000,5725.000000
unique,120,5,79,92,NaN,NaN,NaN,NaN
top,2016-01-01,Norte,Instituto Português de Oncologia de Coimbra F. G.,"38.0162314, -8.6956768",NaN,NaN,NaN,NaN
freq,49,1885,120,96,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,1872.395983,2201.781659,2020.394585,6.499039
std,NaN,NaN,NaN,NaN,1886.747865,2170.172314,2.836003,3.452818
min,NaN,NaN,NaN,NaN,0.000000,0.000000,2016.000000,1.000000
25%,NaN,NaN,NaN,NaN,482.000000,615.000000,2018.000000,3.000000
50%,NaN,NaN,NaN,NaN,1275.000000,1524.000000,2020.000000,6.000000
75%,NaN,NaN,NaN,NaN,2707.000000,3118.000000,2023.000000,9.000000
max,NaN,NaN,NaN,NaN,13197.000000,14472.000000,2025.000000,12.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **internamento_hospitalar**

### General Info
- **Number of Rows:** 15666
- **Number of Columns:** 9

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 15666 entries, 0 to 15665
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   tempo                   15666 non-null  str
 1   regiao                  15666 non-null  str
 2   instituicao             15666 non-null  str
 3   localizacao_geografica  15666 non-null  str
 4   tipo_de_especialidade   15666 non-null  str
 5   doentes_saidos          15666 non-null  float64
 6   dias_de_internamento    15666 non-null  float64
 7   ano                     15666 non-null  int64
 8   mes                     15666 non-null  int64
dtypes: float64(2), int64(2), str(5)
memory usage: 1.1 MB

### Data Sample (First 5 Rows)

,tempo,regiao,instituicao,localizacao_geografica,tipo_de_especialidade,doentes_saidos,dias_de_internamento,ano,mes
0,2024-01-01,Norte,Instituto Português de Oncologia do Porto F. G.,"41.1811, -8.60469",Especialidade Cirurgica,530.0,4130.0,2024,1
1,2024-01-01,Lisboa e Vale do Tejo,Unidade Local de Saúde da Arrábida,"38.529351, -8.881073",Especialidade Cirurgica,374.0,2648.0,2024,1
2,2024-01-01,Norte,Unidade Local de Saúde de Braga,"41.562328338623, -8.3",Especialidade Cirurgica,1103.0,8161.0,2024,1
3,2024-01-01,Centro,Unidade Local de Saúde de Dão-Lafões,"40.6509, -7.91039",Especialidade Cirurgica,797.0,5588.0,2024,1
4,2024-01-01,Norte,Unidade Local de Saúde de Matosinhos,"41.181859, -8.663374",Especialidade Cirurgica,554.0,3638.0,2024,1

### Descriptive Statistics

,tempo,regiao,instituicao,localizacao_geografica,tipo_de_especialidade,doentes_saidos,dias_de_internamento,ano,mes
count,15666,15666,15666,15666,15666,15666.000000,15666.000000,15666.000000,15666.000000
unique,120,5,78,91,3,NaN,NaN,NaN,NaN
top,2021-01-01,Norte,Instituto Português de Oncologia do Porto F. G.,"40.2804158, -7.4922407",Especialidade Médica,NaN,NaN,NaN,NaN
freq,133,5246,360,288,5543,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,3180.962913,27444.230308,2020.464956,6.502426
std,NaN,NaN,NaN,NaN,NaN,3943.025614,33115.765170,2.857966,3.451663
min,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,2016.000000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,427.000000,5032.000000,2018.000000,4.000000
50%,NaN,NaN,NaN,NaN,NaN,1744.000000,15733.500000,2020.000000,7.000000
75%,NaN,NaN,NaN,NaN,NaN,4512.000000,36698.750000,2023.000000,10.000000
max,NaN,NaN,NaN,NaN,NaN,33427.000000,259313.000000,2025.000000,12.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **utentes_cuidados_primarios**

### General Info
- **Number of Rows:** 6216
- **Number of Columns:** 15

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 6216 entries, 0 to 6215
Data columns (total 15 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   periodo                                                         6216 non-null   str
 1   ars                                                             6216 non-null   str
 2   aces                                                            6216 non-null   str
 3   localizacao_geografica                                          6216 non-null   str
 4   utentes_inscritos_csp                                           6216 non-null   int64
 5   total_utentes_com_mdf_atribuido                                 6216 non-null   int64
 6   total_utentes_com_mdf_atribuido0                                6216 non-null   float64
 7   total_utentes_sem_mdf_atribuido                                 6216 non-null   int64
 8   total_utentes_sem_mdf_atribuido0                                6216 non-null   float64
 9   total_utentes_sem_mdf_atribuido_por_opcao                       6216 non-null   int64
 10  total_utentes_sem_mdf_atribuido_por_opcao0                      6216 non-null   float64
 11  taxa_de_utilizacao_consultas_medicas_1_ano_todos_os_utentes     6216 non-null   float64
 12  taxa_de_utilizacao_consultas_medicas_1_ano_nos_utentes_sem_mdf  6216 non-null   float64
 13  ano                                                             6216 non-null   int64
 14  mes                                                             6216 non-null   int64
dtypes: float64(5), int64(6), str(4)
memory usage: 728.6 KB

### Data Sample (First 5 Rows)

,periodo,ars,aces,localizacao_geografica,utentes_inscritos_csp,total_utentes_com_mdf_atribuido,total_utentes_com_mdf_atribuido0,total_utentes_sem_mdf_atribuido,total_utentes_sem_mdf_atribuido0,total_utentes_sem_mdf_atribuido_por_opcao,total_utentes_sem_mdf_atribuido_por_opcao0,taxa_de_utilizacao_consultas_medicas_1_ano_todos_os_utentes,taxa_de_utilizacao_consultas_medicas_1_ano_nos_utentes_sem_mdf,ano,mes
0,2016-01-01,Algarve,ACES Algarve Barlavento,"37.1387554, -8.5445093",159567,104459,65.46,54259,34.00,849,0.53,61.0193,48.4986,2016,1
1,2016-01-01,Centro,ACES Baixo Mondego,"40.2150023, -8.4071805",383001,366903,95.80,14351,3.75,1747,0.46,60.1099,24.7643,2016,1
2,2016-01-01,Centro,ACES Beira Interior Sul,"39.8211367, -7.5036651",73751,71872,97.45,1420,1.93,459,0.62,69.0399,26.9402,2016,1
3,2016-01-01,Centro,ACES Guarda,"40.5353285, -7.2724426",152281,141859,93.16,9100,5.98,1322,0.87,71.9567,53.6963,2016,1
4,2016-01-01,Lisboa e Vale do Tejo,ACES Almada / Seixal,"38.6678522, -9.1875777",340054,282078,82.95,57316,16.85,660,0.19,64.4227,36.8498,2016,1

### Descriptive Statistics

,periodo,ars,aces,localizacao_geografica,utentes_inscritos_csp,total_utentes_com_mdf_atribuido,total_utentes_com_mdf_atribuido0,total_utentes_sem_mdf_atribuido,total_utentes_sem_mdf_atribuido0,total_utentes_sem_mdf_atribuido_por_opcao,total_utentes_sem_mdf_atribuido_por_opcao0,taxa_de_utilizacao_consultas_medicas_1_ano_todos_os_utentes,taxa_de_utilizacao_consultas_medicas_1_ano_nos_utentes_sem_mdf,ano,mes
count,6216,6216,6216,6216,6216.000000,6216.000000,6216.000000,6216.000000,6216.000000,6216.000000,6216.000000,6216.000000,6216.000000,6216.000000,6216.00000
unique,120,5,95,103,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2016-01-01,Norte,ACES Algarve Barlavento,"39.7495331, -8.807683",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,55,2640,96,98,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,199722.576737,177346.787967,90.215542,21909.413932,9.548134,466.374839,0.236338,68.920771,47.853881,2020.252896,6.50000
std,NaN,NaN,NaN,NaN,95799.323362,82301.667590,10.234073,28896.145634,10.193068,629.909822,0.295408,7.552777,16.253814,2.774161,3.45233
min,NaN,NaN,NaN,NaN,30493.000000,20878.000000,49.200000,0.000000,0.000000,0.000000,0.000000,48.091500,0.000000,2016.000000,1.00000
25%,NaN,NaN,NaN,NaN,124857.750000,119812.000000,84.797500,2822.750000,1.820000,67.000000,0.040000,62.821125,36.092125,2018.000000,3.75000
50%,NaN,NaN,NaN,NaN,176503.000000,161520.000000,94.890000,8194.500000,4.910000,235.000000,0.140000,71.462450,48.384145,2020.000000,6.50000
75%,NaN,NaN,NaN,NaN,249230.750000,226174.750000,97.982500,32955.500000,14.870000,629.000000,0.310000,74.664575,60.967500,2023.000000,9.25000
max,NaN,NaN,NaN,NaN,573440.000000,485790.000000,100.000000,192870.000000,50.660000,7595.000000,4.860000,81.882700,84.019200,2025.000000,12.00000

### Missing Values

'None found.'

<br>

---
# Dataset: **consultas**

### General Info
- **Number of Rows:** 5725
- **Number of Columns:** 10

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 5725 entries, 0 to 5724
Data columns (total 10 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   tempo                          5725 non-null   str
 1   periodo_format_2               5725 non-null   str
 2   regiao                         5725 non-null   str
 3   instituicao                    5725 non-null   str
 4   localizacao_geografica         5725 non-null   str
 5   no_de_consultas_medicas_total  5725 non-null   int64
 6   no_de_primeiras_consultas      5725 non-null   int64
 7   no_de_consultas_subsequentes   5725 non-null   int64
 8   ano                            5725 non-null   int64
 9   mes                            5725 non-null   int64
dtypes: int64(5), str(5)
memory usage: 447.4 KB

### Data Sample (First 5 Rows)

,tempo,periodo_format_2,regiao,instituicao,localizacao_geografica,no_de_consultas_medicas_total,no_de_primeiras_consultas,no_de_consultas_subsequentes,ano,mes
0,2016-01-01,2016/01/01,Centro,Hospital Arcebispo João Crisóstomo,"40.3470015, -8.5933462",1642,744,898,2016,1
1,2016-01-01,2016/01/01,Centro,Unidade Local de Saúde da Guarda,"40.5309916, -7.2734793",9150,3101,6049,2016,1
2,2016-01-01,2016/01/01,Centro,Unidade Local de Saúde de Castelo Branco,"39.8212263, -7.4981271",7581,2292,5289,2016,1
3,2016-01-01,2016/01/01,Lisboa e Vale do Tejo,Centro Hospitalar do Oeste,"39.4054629, -9.1258493",11807,3953,7854,2016,1
4,2016-01-01,2016/01/01,Lisboa e Vale do Tejo,Hospital de Vila Franca de Xira,"38.977235, -8.984506",13250,5012,8238,2016,1

### Descriptive Statistics

,tempo,periodo_format_2,regiao,instituicao,localizacao_geografica,no_de_consultas_medicas_total,no_de_primeiras_consultas,no_de_consultas_subsequentes,ano,mes
count,5725,5725,5725,5725,5725,5.725000e+03,5725.000000,5725.000000,5725.000000,5725.000000
unique,120,120,5,79,92,NaN,NaN,NaN,NaN,NaN
top,2016-01-01,2016/01/01,Norte,Unidade Local de Saúde da Guarda,"40.3470015, -8.5933462",NaN,NaN,NaN,NaN,NaN
freq,49,49,1885,120,96,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,1.450905e+05,41136.025153,103954.504629,2020.394585,6.499039
std,NaN,NaN,NaN,NaN,NaN,1.533521e+05,41433.363624,112686.512092,2.836003,3.452818
min,NaN,NaN,NaN,NaN,NaN,3.350000e+02,125.000000,194.000000,2016.000000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,4.289400e+04,12799.000000,30091.000000,2018.000000,3.000000
50%,NaN,NaN,NaN,NaN,NaN,9.298200e+04,27962.000000,64787.000000,2020.000000,6.000000
75%,NaN,NaN,NaN,NaN,NaN,1.919700e+05,55049.000000,137950.000000,2023.000000,9.000000
max,NaN,NaN,NaN,NaN,NaN,1.000962e+06,259515.000000,741447.000000,2025.000000,12.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **cirurgias**

### General Info
- **Number of Rows:** 5448
- **Number of Columns:** 10

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 5448 entries, 0 to 5447
Data columns (total 10 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   tempo                                      5448 non-null   str
 1   regiao                                     5448 non-null   str
 2   instituicao                                5448 non-null   str
 3   localizacao_geografica                     5448 non-null   str
 4   no_intervencoes_cirurgicas_programadas     5448 non-null   int64
 5   no_intervencoes_cirurgicas_convencionais   5448 non-null   float64
 6   no_intervencoes_cirurgicas_de_ambulatorio  5448 non-null   int64
 7   no_intervencoes_cirurgicas_urgentes        5448 non-null   float64
 8   ano                                        5448 non-null   int64
 9   mes                                        5448 non-null   int64
dtypes: float64(2), int64(4), str(4)
memory usage: 425.8 KB

### Data Sample (First 5 Rows)

,tempo,regiao,instituicao,localizacao_geografica,no_intervencoes_cirurgicas_programadas,no_intervencoes_cirurgicas_convencionais,no_intervencoes_cirurgicas_de_ambulatorio,no_intervencoes_cirurgicas_urgentes,ano,mes
0,2016-01-01,Alentejo,Unidade Local de Saúde do Baixo Alentejo,"38.014123, -7.8721227",318,139.0,179,108.0,2016,1
1,2016-01-01,Alentejo,Unidade Local de Saúde do Norte Alentejano,"39.3003425, -7.4263845",492,172.0,320,71.0,2016,1
2,2016-01-01,Centro,Unidade Local de Saúde de Coimbra,"40.2191523, -8.4098211",3069,1378.0,1691,563.0,2016,1
3,2016-01-01,Centro,Instituto Português de Oncologia de Coimbra F. G.,"40.2162514, -8.4103814",386,238.0,148,0.0,2016,1
4,2016-01-01,Lisboa e Vale do Tejo,Centro Hospitalar de Setúbal,"38.5283754, -8.8818638",691,226.0,465,151.0,2016,1

### Descriptive Statistics

,tempo,regiao,instituicao,localizacao_geografica,no_intervencoes_cirurgicas_programadas,no_intervencoes_cirurgicas_convencionais,no_intervencoes_cirurgicas_de_ambulatorio,no_intervencoes_cirurgicas_urgentes,ano,mes
count,5448,5448,5448,5448,5448.000000,5448.000000,5448.000000,5448.000000,5448.000000,5448.000000
unique,120,5,76,89,NaN,NaN,NaN,NaN,NaN,NaN
top,2016-01-01,Norte,Unidade Local de Saúde do Baixo Alentejo,"38.014123, -7.8721227",NaN,NaN,NaN,NaN,NaN,NaN
freq,46,1800,120,96,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,7664.935756,2467.772394,5197.163363,1163.287078,2020.447137,6.500000
std,NaN,NaN,NaN,NaN,7868.957216,2725.995183,5338.436570,1257.228099,2.853590,3.452369
min,NaN,NaN,NaN,NaN,46.000000,0.000000,35.000000,0.000000,2016.000000,1.000000
25%,NaN,NaN,NaN,NaN,2459.500000,729.750000,1544.250000,318.000000,2018.000000,3.750000
50%,NaN,NaN,NaN,NaN,5064.000000,1565.500000,3389.000000,772.000000,2020.000000,6.500000
75%,NaN,NaN,NaN,NaN,9962.000000,3137.000000,6887.000000,1564.000000,2023.000000,9.250000
max,NaN,NaN,NaN,NaN,59252.000000,20417.000000,38967.000000,8972.000000,2025.000000,12.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **divida**

### General Info
- **Number of Rows:** 6441
- **Number of Columns:** 9

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 6441 entries, 0 to 6440
Data columns (total 9 columns):
 #   Column                                Non-Null Count  Dtype
---  ------                                --------------  -----
 0   periodo                               6441 non-null   str
 1   regiao                                6441 non-null   str
 2   entidade                              6441 non-null   str
 3   localizacao_geografica                6441 non-null   str
 4   divida_total_fornecedores_externos    6441 non-null   float64
 5   divida_vencida_fornecedores_externos  6441 non-null   float64
 6   pagamentos_em_atraso                  6441 non-null   float64
 7   ano                                   6441 non-null   int64
 8   mes                                   6441 non-null   int64
dtypes: float64(3), int64(2), str(4)
memory usage: 453.0 KB

### Data Sample (First 5 Rows)

,periodo,regiao,entidade,localizacao_geografica,divida_total_fornecedores_externos,divida_vencida_fornecedores_externos,pagamentos_em_atraso,ano,mes
0,2016-01-01,Serviços Centrais,"Administração Central do Sistema de Saúde, I.P","38.759209, -9.148981",8.414604e+04,84146.04,0.00,2016,1
1,2016-01-01,Centro,Administração Regional de Saúde do Centro,"40.2038123, -8.4216163",8.468318e+07,61956154.52,10321628.69,2016,1
2,2016-01-01,Norte,Administração Regional de Saúde do Norte,"41.1576321, -8.6066408",1.599338e+08,68966910.64,-227773.70,2016,1
3,2016-01-01,Lisboa e Vale do Tejo,Centro Hospitalar de Lisboa - Zona Ocidental,"38.708454, -9.216985",8.810537e+07,54111384.64,34150915.88,2016,1
4,2016-01-01,Norte,Unidade Local de Saúde de São João,"41.1831056, -8.6010558",4.333242e+07,9592106.07,26839.65,2016,1

### Descriptive Statistics

,periodo,regiao,entidade,localizacao_geografica,divida_total_fornecedores_externos,divida_vencida_fornecedores_externos,pagamentos_em_atraso,ano,mes
count,6441,6441,6441,6441,6.441000e+03,6.441000e+03,6.441000e+03,6441.000000,6441.000000
unique,120,6,101,58,NaN,NaN,NaN,NaN,NaN
top,2023-01-01,Norte,Unidade Local de Saúde de São João,"39.4054629, -9.1258493",NaN,NaN,NaN,NaN,NaN
freq,59,1976,120,196,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,3.428525e+07,1.972507e+07,9.301327e+06,2020.469337,6.528955
std,NaN,NaN,NaN,NaN,4.244468e+07,2.861869e+07,1.849770e+07,2.842288,3.457166
min,NaN,NaN,NaN,NaN,-1.295877e+07,-3.002279e+07,-7.523691e+06,2016.000000,1.000000
25%,NaN,NaN,NaN,NaN,6.566637e+06,1.482039e+06,1.801498e+04,2018.000000,4.000000
50%,NaN,NaN,NaN,NaN,2.081606e+07,1.103583e+07,2.492205e+06,2020.000000,7.000000
75%,NaN,NaN,NaN,NaN,4.283633e+07,2.448172e+07,1.057387e+07,2023.000000,10.000000
max,NaN,NaN,NaN,NaN,3.206778e+08,2.503392e+08,1.993909e+08,2025.000000,12.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **atendimento_urgencia**

### General Info
- **Number of Rows:** 4801
- **Number of Columns:** 9

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 4801 entries, 0 to 4800
Data columns (total 9 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   tempo                   4801 non-null   str
 1   periodoformat2          4801 non-null   str
 2   regiao                  4801 non-null   str
 3   instituicao             4801 non-null   str
 4   localizacao_geografica  4801 non-null   str
 5   urgencias_geral         4801 non-null   float64
 6   total_urgencias         4801 non-null   float64
 7   ano                     4801 non-null   int64
 8   mes                     4801 non-null   int64
dtypes: float64(2), int64(2), str(5)
memory usage: 337.7 KB

### Data Sample (First 5 Rows)

,tempo,periodoformat2,regiao,instituicao,localizacao_geografica,urgencias_geral,total_urgencias,ano,mes
0,2024-01-01,2024/01/01,Lisboa e Vale do Tejo,Unidade Local de Saúde de Almada-Seixal,"38.67381, -9.17597",6831.0,10899.0,2024,1
1,2024-01-01,2024/01/01,Lisboa e Vale do Tejo,Unidade Local de Saúde de Amadora/Sintra,"38.7436332060551, -9.0",13917.0,18488.0,2024,1
2,2024-01-01,2024/01/01,Centro,Unidade Local de Saúde de Dão-Lafões,"40.6509, -7.91039",8917.0,13104.0,2024,1
3,2024-01-01,2024/01/01,Norte,Unidade Local de Saúde de Entre Douro e Vouga,"40.9295, -8.54567",15899.0,19249.0,2024,1
4,2024-01-01,2024/01/01,Lisboa e Vale do Tejo,Unidade Local de Saúde de Lisboa Ocidental,"38.7084, -9.21711",6569.0,10051.0,2024,1

### Descriptive Statistics

,tempo,periodoformat2,regiao,instituicao,localizacao_geografica,urgencias_geral,total_urgencias,ano,mes
count,4801,4801,4801,4801,4801,4801.000000,4801.000000,4801.000000,4801.000000
unique,120,120,5,71,81,NaN,NaN,NaN,NaN
top,2016-08-01,2016/08/01,Norte,Unidade Local de Saúde de São José,"39.3003425, -7.4263845",NaN,NaN,NaN,NaN
freq,41,41,1680,120,96,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,NaN,58768.131848,79964.477401,2020.499063,6.500312
std,NaN,NaN,NaN,NaN,NaN,42181.351562,58790.536444,2.873015,3.452120
min,NaN,NaN,NaN,NaN,NaN,0.000000,0.000000,2016.000000,1.000000
25%,NaN,NaN,NaN,NaN,NaN,26166.000000,35175.000000,2018.000000,4.000000
50%,NaN,NaN,NaN,NaN,NaN,49828.000000,66435.000000,2020.000000,7.000000
75%,NaN,NaN,NaN,NaN,NaN,81608.000000,111733.000000,2023.000000,9.000000
max,NaN,NaN,NaN,NaN,NaN,292003.000000,380759.000000,2025.000000,12.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **dados_financeiros**

### General Info
- **Number of Rows:** 5386
- **Number of Columns:** 11

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 5386 entries, 0 to 5385
Data columns (total 11 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   tempo                     5386 non-null   str
 1   regiao                    5386 non-null   str
 2   entidade                  5386 non-null   str
 3   localizacao_geografica    5386 non-null   str
 4   ebitda                    5386 non-null   float64
 5   gastos_operacionais       5386 non-null   float64
 6   rendimentos_operacionais  5386 non-null   float64
 7   resultado_liquido         5386 non-null   float64
 8   resultados_operacionais   5386 non-null   float64
 9   ano                       5386 non-null   int64
 10  mes                       5386 non-null   int64
dtypes: float64(5), int64(2), str(4)
memory usage: 463.0 KB

### Data Sample (First 5 Rows)

,tempo,regiao,entidade,localizacao_geografica,ebitda,gastos_operacionais,rendimentos_operacionais,resultado_liquido,resultados_operacionais,ano,mes
0,2016-01-01,Lisboa e Vale do Tejo,Centro Hospitalar de Setúbal,"38.5283754, -8.8818638",-1616312.61,9376799.55,7516433.04,-1633586.72,-1860366.51,2016,1
1,2016-01-01,Lisboa e Vale do Tejo,Centro Hospitalar do Barreiro - Montijo,"38.6554005, -9.0592392",-535952.19,6487139.62,5606640.06,-861615.88,-880499.56,2016,1
2,2016-01-01,Centro,Unidade Local de Saúde de Coimbra,"40.2191523, -8.4098211",-30428.71,33489298.70,32933120.24,-331818.53,-556178.46,2016,1
3,2016-01-01,Lisboa e Vale do Tejo,Centro Hospitalar Psiquiátrico de Lisboa,"38.7569771, -9.1460705",506911.32,1849972.32,1981439.29,124214.13,131466.97,2016,1
4,2016-01-01,Centro,Hospital Distrital Figueira da Foz,"40.117897, -8.8586755",137165.46,2268745.01,2358151.16,89320.28,89406.15,2016,1

### Descriptive Statistics

,tempo,regiao,entidade,localizacao_geografica,ebitda,gastos_operacionais,rendimentos_operacionais,resultado_liquido,resultados_operacionais,ano,mes
count,5386,5386,5386,5386,5.386000e+03,5.386000e+03,5.386000e+03,5.386000e+03,5.386000e+03,5386.000000,5386.000000
unique,119,6,90,49,NaN,NaN,NaN,NaN,NaN,NaN,NaN
top,2022-12-01,Norte,Unidade Local de Saúde de São João,"39.4054629, -9.1258493",NaN,NaN,NaN,NaN,NaN,NaN,NaN
freq,51,1844,119,192,NaN,NaN,NaN,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,-1.093171e+07,9.725204e+07,8.443794e+07,-1.289023e+07,-1.295287e+07,2020.516153,6.475121
std,NaN,NaN,NaN,NaN,1.681222e+07,1.158498e+08,1.003217e+08,1.854905e+07,1.856817e+07,2.834038,3.435388
min,NaN,NaN,NaN,NaN,-1.688819e+08,0.000000e+00,-6.411547e+06,-1.893682e+08,-1.886743e+08,2016.000000,1.000000
25%,NaN,NaN,NaN,NaN,-1.478709e+07,2.300698e+07,2.026929e+07,-1.725451e+07,-1.727356e+07,2018.000000,3.000000
50%,NaN,NaN,NaN,NaN,-5.784463e+06,6.069498e+07,5.277181e+07,-7.259082e+06,-7.323551e+06,2021.000000,6.000000
75%,NaN,NaN,NaN,NaN,-8.876571e+05,1.221651e+08,1.069935e+08,-1.503650e+06,-1.558152e+06,2023.000000,9.000000
max,NaN,NaN,NaN,NaN,1.379784e+08,1.006721e+09,8.508979e+08,1.380264e+08,1.379784e+08,2025.000000,12.000000

### Missing Values

'None found.'

<br>

---
# Dataset: **medicamento_hospitalar**

### General Info
- **Number of Rows:** 540
- **Number of Columns:** 5

### Data Types and Non-Null Counts

<class 'pandas.DataFrame'>
RangeIndex: 540 entries, 0 to 539
Data columns (total 5 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   tempo                    540 non-null    str
 1   regiao                   540 non-null    str
 2   encargos_sns_hospitalar  540 non-null    float64
 3   ano                      540 non-null    int64
 4   mes                      540 non-null    int64
dtypes: float64(1), int64(2), str(2)
memory usage: 21.2 KB

### Data Sample (First 5 Rows)

        tempo                 regiao  encargos_sns_hospitalar   ano  mes
0  2016-02-01                Algarve               4147587.77  2016    2
1  2016-02-01  Lisboa e Vale do Tejo              53305400.94  2016    2
2  2016-05-01                  Norte              28785991.26  2016    5
3  2016-06-01  Lisboa e Vale do Tejo              51407261.46  2016    6
4  2016-11-01                 Centro              18799309.91  2016   11

### Descriptive Statistics

             tempo   regiao  encargos_sns_hospitalar          ano         mes
count          540      540             5.400000e+02   540.000000  540.000000
unique         108        5                      NaN          NaN         NaN
top     2016-02-01  Algarve                      NaN          NaN         NaN
freq             5      108                      NaN          NaN         NaN
mean           NaN      NaN             2.604642e+07  2020.000000    6.500000
std            NaN      NaN             2.334719e+07     2.584383    3.455253
min            NaN      NaN             6.097610e+05  2016.000000    1.000000
25%            NaN      NaN             4.111780e+06  2018.000000    3.750000
50%            NaN      NaN             1.875981e+07  2020.000000    6.500000
75%            NaN      NaN             4.738768e+07  2022.000000    9.250000
max            NaN      NaN             8.782092e+07  2024.000000   12.000000

### Missing Values

'None found.'